#spring.datasource.url=jdbc:mysql://localhost:3306/cars_db
spring.datasource.url=jdbc:mysql://mysql:3306/cars_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
#server.error.include-message=always
#server.error.include-binding-errors=always

jwt.secret=mysecretkeymys1234567854ecretkey
jwt.expiration=3600000

# Helps when DB is a bit slow to start
spring.datasource.hikari.initializationFailTimeout=60000
spring.datasource.hikari.connectionTimeout=60000